name: Deploy to VM

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key
        chmod 600 private_key

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no -i private_key azureuser@74.235.199.79 << 'EOF'
          echo "Current directory:"
          pwd
          echo "Directory listing:"
          ls -la
          echo "Changing to application directory:"
          cd /correct/path/to/your/app || exit
          echo "In application directory:"
          pwd
          echo "Pulling latest changes from git:"
          git pull origin master
          echo "Installing npm dependencies:"
          npm install
          echo "Stopping existing node process:"
          sudo pkill node || true
          echo "Starting new node process:"
          sudo nohup node server.js &
          exit
        EOF
